### PR TITLE
🧠 Logic: 🐛 Fix `consult/1` base64 decoding 

### LINKED ISSUE #384: 🧠 Logic: 🗂️ on virtual file URI : allow query non base64 encoded wasm contract response
## 📝 Description

#305 introduce the virtual file system allowing us to query smart contract through an URI and consult result into prolog. It was designed that the result of the smart contract query assume is an objectarium smart contract, in consequence, objectarium query response is a JSON containing base64 encoded data. When we call any `cosmwasm:` URI, the response is always converted to json and decoded to data from base64. 

```
cosmwasm:{contract_name}:{contract_address}?query={contract_query}.
```

## 💡 Proposed solution

We could add a new query parameter called `options` allowing pass a set of options to the virtual file system to handle the query. For this particular case, I suggest to add an option : `decode_base64` that indicate the result is base64 encoded and we need to decode it before send the data to the requester.  

```
cosmwasm:{contract_name}:{contract_address}?query={contract_query}[&options=[decode_base64]].
```

## 🤯 Breaking change

Considering this option is not by default, current deployed prolog that use the `consult/1` predicate and call an objectarium contract will no longer working if we didn't indicate the `decode_base64` option. A solution would be to override the `consult/1` predicate implemented by `ichiban/prolog` library and use our own `consult/1` by adding automatically the `decode_base64` option if it's an objectarium contract, we could indicate as deprecated until we update all our references in tutorials, nemeton program, documentations, ... and remove this hack on future release. 

## 🔗 Related link and predicate
- #379 `open/4` use virtual file system and need to query wasm contract without the base64 decoding.

## Let's discuss on it ;)

### PR DESCRIPTION
**Pull request by bdeneux**
Fixes #384.

### CODE REVIEW

File: x/logic/predicate/file.go [hunk 1]
```diff
@@ -57,6 +61,62 @@ func SourceFile(vm *engine.VM, file engine.Term, cont engine.Cont, env *engine.E
...
 
+func Consult(vm *engine.VM, files engine.Term, k engine.Cont, env *engine.Env) *engine.Promise {
+	var filenames []engine.Term
+	iter := engine.ListIterator{List: files, Env: env}
+	for iter.Next() {
+		filenames = append(filenames, iter.Current())
+	}
+	if err := iter.Err(); err != nil {
+		filenames = []engine.Term{files}
+	}
```
Comment (amimart) [inline x/logic/predicate/file.go:72]: I saw that the original implementation doesn't handle the error, but I don't see any reason justifying this choice.

Maybe it'd better to avoid silencing it, what do you think?

File: x/logic/predicate/file.go [hunk 2]
```diff
@@ -57,6 +61,62 @@ func SourceFile(vm *engine.VM, file engine.Term, cont engine.Cont, env *engine.E
...
+		}
+
+		return k(env)
+	})
+}
+
+func ensureLoaded(ctx context.Context, vm *engine.VM, file engine.Term, env *engine.Env) error {
+	switch f := env.Resolve(file).(type) {
+	case engine.Variable:
+		return fmt.Errorf("file could not be a variable")
```
Comment (amimart) [inline x/logic/predicate/file.go:88]:
```suggestion
		return fmt.Errorf("file cannot be a variable")
```

File: x/logic/predicate/file.go [hunk 3]
```diff
@@ -57,6 +61,62 @@ func SourceFile(vm *engine.VM, file engine.Term, cont engine.Cont, env *engine.E
...
+		}
+
+		// only base64 decode if the result of file's read is a json string because cosmwasm query return json with
+		// base64 encoded file.
+		var program string
+		err = json.Unmarshal(b, &program)
+		if err == nil {
+			b, err = base64.StdEncoding.DecodeString(program)
+			if err != nil {
+				return fmt.Errorf("failed decode wasm base64 respone: %w", err)
```
Comment (amimart) [inline x/logic/predicate/file.go:103]:
```suggestion
				return fmt.Errorf("couldn't decode base64 content: %w", err)
```

**Review by amimart — CHANGES_REQUESTED** [review]
That's really nice, thanks! Always appreciate reflect incantations 🙄 

I've some remarks regarding error messages and also an open question regarding eventual iterator error, let's discuss it :)

**Review by amimart — CHANGES_REQUESTED** [review]
Oh and as the changes on the virtual file system and the consult are breaking changes, I think the related commits shall contains the breaking change marker (i.e. `!`) after the commit's types :)

File: x/logic/predicate/file.go (hunk 1 above)
Comment (bdeneux) [reply x/logic/predicate/file.go:72]: @amimart In fact, the error is handled (`err != nil` 😜) but it's because the `files` term can be a list or a string, in case is a string, iterator throw an error and it's transformed into a list of single filename.

File: x/logic/predicate/file_test.go [hunk 4]
```diff
@@ -135,6 +135,152 @@ func TestSourceFile(t *testing.T) {
...
+				wantError:   fmt.Errorf("consult/1: invalid domain for given file"),
+			},
+			{
+				files: map[string][]byte{
+					"file": []byte("\"$FsYyhYKSA6LSAgWCBpcyAxMDAgKyAyMDAu\""),
+				},
+				interpreter: testutil.NewComprehensiveInterpreterMust,
+				query:       "consult(file).",
+				wantSuccess: false,
+				wantError:   fmt.Errorf("consult/1: failed decode wasm base64 respone: illegal base64 data at input byte 0"),
```
Comment (bdeneux) [inline x/logic/predicate/file_test.go:256]:
```suggestion
				wantError:   fmt.Errorf("consult/1: couldn't decode base64 content: illegal base64 data at input byte 0"),
```

File: x/logic/predicate/file.go (hunk 1 above)
Comment (amimart) [reply x/logic/predicate/file.go:72]: Oh I see, the error exists when we have a string instead of a list. This is ugly!

**Review by amimart — APPROVED** [review]
That's great thanks! 💪

**Comment by ccamel** [comment]
Apologies for the delay on this matter. I have some concerns about the proposed approach.

I would have incorporated instructions for Base64 decoding in the URI itself, as it carries the protocol elements. IMHO, the responsibility for decoding should lie with the VFS rather than the consuming function (as initially proposed by #384). And we could consider to have Base64 decoding set as the default option for the considered URI, to avoid any breaking changes, I presume. as it stands, the current approach appears to be quite limiting. What are your thoughts on this?

**Comment by bdeneux** [comment]
@ccamel Yes I'm agree, I prefer to make the logical on URI that will hold this decoding information but we have choose this approach to avoid breaking change. Otherwise, make the decoding by default on this URI and add an option to remove the decoding should be a good compromise. 

Before continue, which URI parameter could be used to deactivate encoding ? `&options=no_decoding`, `&decoding=none`, or something else ?

**Comment by amimart** [comment]
> I would have incorporated instructions for Base64 decoding in the URI itself, as it carries the protocol elements. IMHO, the responsibility for decoding should lie with the VFS rather than the consuming function (as initially proposed by #384). And we could consider to have Base64 decoding set as the default option for the considered URI, to avoid any breaking changes, I presume. as it stands, the current approach appears to be quite limiting. What are your thoughts on this?

Well, I'm divided..

Regarding the Base64 at the VFS level, the need appeared using a consult loading sources from the objectarium smart contract which return the data in Base64, this seems to me far from the nominal case and it hardly justify this behavior on the VFS, in my opinion.

On the other side this is weird to have the Base64 decoding in the consult, but to prevent any limitations the implementation here supports both Base64 and raw data.

However, I'm not against going on the URI param way I you both prefer :)

**Comment by ccamel** [comment]
> Before continue, which URI parameter could be used to deactivate encoding ? `&options=no_decoding`, `&decoding=none`, or something else ?

One way to declare the intention of base64 decoding right in the URI would be: `?base64Decode=true`. Or the opposite if the default behavior is systematic decoding: `?base64Decode=false`.
